-
  name: Install required packages
  hosts:  all
  connection: ssh
  remote_user: root
  become: yes
  become_method: sudo 
    
  tasks:
  - name: install java
    yum:
      name: java
      state: present
      
  - name: Install tomcat
    yum:
      name: tomcat
      state: present
      
     
  - name: "Add Jenkins repository"
    get_url: url="http://pkg.jenkins-ci.org/redhat/jenkins.repo" dest="/etc/yum.repos.d/jenkins.repo"

  - name: "Import Jenkins key"
    command: "rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key"
    
  - name: "Install Jenkins"
    yum:
      name: jenkins
      state: present
    
  - name: "Start Jenkins"
    service: name="jenkins" state="started"

  #- name: Disable the firewall
  #  command: firewall-cmd --permanent --service=jenkins --set-short="Jenkins Service Ports" && firewall-cmd --permanent --service=jenkins --set-description="Jenkins service firewalld port exceptions" && firewall-cmd --permanent --service=jenkins --add-port=8080/tcp && firewall-cmd --permanent --add-service=jenkins && firewall-cmd --zone=public --add-service=http --permanent && firewall-cmd --reload
