-
  name: Install required packages
  hosts:  all
  connection: ssh
  remote_user: root
  become: yes
  become_method: sudo 
    
  tasks:
  - name: install java
      yum:
        name: java
        state: present
      
  - name: Install and start tomcat service
      yum:
        name: tomcat
      service:
          name: tomcat
          state: present
    
  - name: "Add Jenkins repository"
      get_url: url="http://pkg.jenkins-ci.org/redhat/jenkins.repo" dest="/etc/yum.repos.d/jenkins.repo"

  - name: "Import Jenkins key"
      command: "rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key"
    
  - name: "Install Jenkins"
      yum:
        name: jenkins
        state: present
    
  - name: "Start Jenkins"
      service: name="jenkins" state="started"
